### ISSUE TITLE
"Let the user take the survey multiple times on a recurring basis" is not working

### ISSUE THREAD

**Issue by asai569** [andre-paraense/survicate-flutter-sdk#11]
**Describe the bug**

"Let the user take the survey multiple times on a recurring basis" is not working

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andre-paraense** [comment]
Hi, @asai569 , thanks for the issue. I am not sure if this is a feature not yet implemented in the package or if this is a bug. What do you think? I will have to investigate it. If you want to make a contribution, feel free to open a PR on this as well, and I will review with you until we are able to integrate.

**Comment by asai569** [comment]
@andre-paraense 
Hi, !
The latest version of this package was updated 7 months ago.
This content has been added to 1.5.0 (2021-11-18) in the "survicate ios SDK".
"Surveys can now be set to appear on a recurring basis. This means respondents can answer the same mobile survey again, and again --on a daily, weekly, monthly, or quarterly basis.
"
From this, I think that 1.5.0 version is not reflected.

**Comment by andre-paraense** [comment]
> @andre-paraense Hi, ! The latest version of this package was updated 7 months ago. This content has been added to 1.5.0 (2021-11-18) in the "survicate ios SDK". "Surveys can now be set to appear on a recurring basis. This means respondents can answer the same mobile survey again, and again --on a daily, weekly, monthly, or quarterly basis. " From this, I think that 1.5.0 version is not reflected.

Ah, OK, so then this should be as simple as bumping the Android/iOS SDK versions! :) 

Will find sometime to do it in the following days. Thanks!

**Comment by asai569** [comment]
> > @andre-paraense Hi, ! The latest version of this package was updated 7 months ago. This content has been added to 1.5.0 (2021-11-18) in the "survicate ios SDK". "Surveys can now be set to appear on a recurring basis. This means respondents can answer the same mobile survey again, and again --on a daily, weekly, monthly, or quarterly basis. " From this, I think that 1.5.0 version is not reflected.
> 
> Ah, OK, so then this should be as simple as bumping the Android/iOS SDK versions! :)
> 
> Will find sometime to do it in the following days. Thanks!

Thank you very much. :)

**Comment by andre-paraense** [comment]
@asai569 the latest version has bumped the android and iOS according to what you had asked. I will close this issue, please reopen if you think it still makes sense.
