### ISSUE TITLE
SurvicateFlutterSdkPlugin.kt: (49, 28): Not nullable value required to call an 'iterator()' method on for-loop range

### ISSUE THREAD

**Issue by Mitsuroseba** [andre-paraense/survicate-flutter-sdk#12]
**Describe the bug**
"flutter build appbundle"

Build for Android breaks with this message.

Simple setup:
`
  SurvicateFlutterSdk survicateFlutterSdk = SurvicateFlutterSdk();
...
survicateFlutterSdk.enterScreen('main');`

Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fb57da5f94 (3 weeks ago) • 2022-05-19 15:50:29 -0700
Engine • revision caaafc5604
Tools • Dart 2.17.1 • DevTools 2.12.2

survicate_flutter_sdk: ^2.1.1

android/app/src/main/AndroidManifest.xml in application scope
"<meta-data android:name="com.survicate.surveys.workspaceKey" android:value="

**Comment by andre-paraense** [comment]
Hello, @Mitsuroseba . This makes sense, nothing has been tested with Flutter 3 yet. Will do soon. Thanks for raising this :)

**Comment by RamithRD** [comment]
@andre-paraense any timeline we can expect the Flutter 3 compatible update? :)

**Comment by andre-paraense** [comment]
Hey, guys, the new version 2.1.2 is building again in Android, after a couple fixes. I will close this one for now, let me know if you have any problems reopening it.
